// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to get information about existing Elasticsearch user. See, https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-get-user.html".
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/Tonkean/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			userDataSecurityUser, err := elasticstack.DataSecurityUser(ctx, &elasticstack.DataSecurityUserArgs{
//				Username: "elastic",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("user", userDataSecurityUser)
//			return nil
//		})
//	}
//
// ```
func DataSecurityUser(ctx *pulumi.Context, args *DataSecurityUserArgs, opts ...pulumi.InvokeOption) (*DataSecurityUserResult, error) {
	var rv DataSecurityUserResult
	err := ctx.Invoke("elasticstack:index/dataSecurityUser:DataSecurityUser", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking DataSecurityUser.
type DataSecurityUserArgs struct {
	// Elasticsearch connection configuration block.
	ElasticsearchConnection *DataSecurityUserElasticsearchConnection `pulumi:"elasticsearchConnection"`
	// An identifier for the user
	Username string `pulumi:"username"`
}

// A collection of values returned by DataSecurityUser.
type DataSecurityUserResult struct {
	// Elasticsearch connection configuration block.
	ElasticsearchConnection *DataSecurityUserElasticsearchConnection `pulumi:"elasticsearchConnection"`
	// The email of the user.
	Email string `pulumi:"email"`
	// Specifies whether the user is enabled. The default value is true.
	Enabled bool `pulumi:"enabled"`
	// The full name of the user.
	FullName string `pulumi:"fullName"`
	// Internal identifier of the resource
	Id string `pulumi:"id"`
	// Arbitrary metadata that you want to associate with the user.
	Metadata string `pulumi:"metadata"`
	// A set of roles the user has. The roles determine the user’s access permissions. Default is [].
	Roles []string `pulumi:"roles"`
	// An identifier for the user
	Username string `pulumi:"username"`
}

func DataSecurityUserOutput(ctx *pulumi.Context, args DataSecurityUserOutputArgs, opts ...pulumi.InvokeOption) DataSecurityUserResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (DataSecurityUserResult, error) {
			args := v.(DataSecurityUserArgs)
			r, err := DataSecurityUser(ctx, &args, opts...)
			var s DataSecurityUserResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(DataSecurityUserResultOutput)
}

// A collection of arguments for invoking DataSecurityUser.
type DataSecurityUserOutputArgs struct {
	// Elasticsearch connection configuration block.
	ElasticsearchConnection DataSecurityUserElasticsearchConnectionPtrInput `pulumi:"elasticsearchConnection"`
	// An identifier for the user
	Username pulumi.StringInput `pulumi:"username"`
}

func (DataSecurityUserOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DataSecurityUserArgs)(nil)).Elem()
}

// A collection of values returned by DataSecurityUser.
type DataSecurityUserResultOutput struct{ *pulumi.OutputState }

func (DataSecurityUserResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DataSecurityUserResult)(nil)).Elem()
}

func (o DataSecurityUserResultOutput) ToDataSecurityUserResultOutput() DataSecurityUserResultOutput {
	return o
}

func (o DataSecurityUserResultOutput) ToDataSecurityUserResultOutputWithContext(ctx context.Context) DataSecurityUserResultOutput {
	return o
}

// Elasticsearch connection configuration block.
func (o DataSecurityUserResultOutput) ElasticsearchConnection() DataSecurityUserElasticsearchConnectionPtrOutput {
	return o.ApplyT(func(v DataSecurityUserResult) *DataSecurityUserElasticsearchConnection {
		return v.ElasticsearchConnection
	}).(DataSecurityUserElasticsearchConnectionPtrOutput)
}

// The email of the user.
func (o DataSecurityUserResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v DataSecurityUserResult) string { return v.Email }).(pulumi.StringOutput)
}

// Specifies whether the user is enabled. The default value is true.
func (o DataSecurityUserResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v DataSecurityUserResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// The full name of the user.
func (o DataSecurityUserResultOutput) FullName() pulumi.StringOutput {
	return o.ApplyT(func(v DataSecurityUserResult) string { return v.FullName }).(pulumi.StringOutput)
}

// Internal identifier of the resource
func (o DataSecurityUserResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v DataSecurityUserResult) string { return v.Id }).(pulumi.StringOutput)
}

// Arbitrary metadata that you want to associate with the user.
func (o DataSecurityUserResultOutput) Metadata() pulumi.StringOutput {
	return o.ApplyT(func(v DataSecurityUserResult) string { return v.Metadata }).(pulumi.StringOutput)
}

// A set of roles the user has. The roles determine the user’s access permissions. Default is [].
func (o DataSecurityUserResultOutput) Roles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v DataSecurityUserResult) []string { return v.Roles }).(pulumi.StringArrayOutput)
}

// An identifier for the user
func (o DataSecurityUserResultOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v DataSecurityUserResult) string { return v.Username }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(DataSecurityUserResultOutput{})
}
