// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Converts a string field by applying a regular expression and a replacement. If the field is an array of string, all members of the array will be converted. If any non-string values are encountered, the processor will throw an exception.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/gsub-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			gsub, err := elasticstack.ElasticstackElasticsearchIngestProcessorGsub(ctx, &elasticstack.ElasticstackElasticsearchIngestProcessorGsubArgs{
//				Field:       "field1",
//				Pattern:     "\\.",
//				Replacement: "-",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = elasticstack.NewElasticstackElasticsearchIngestPipeline(ctx, "myIngestPipeline", &elasticstack.ElasticstackElasticsearchIngestPipelineArgs{
//				Processors: pulumi.StringArray{
//					*pulumi.String(gsub.Json),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func ElasticstackElasticsearchIngestProcessorGsub(ctx *pulumi.Context, args *ElasticstackElasticsearchIngestProcessorGsubArgs, opts ...pulumi.InvokeOption) (*ElasticstackElasticsearchIngestProcessorGsubResult, error) {
	var rv ElasticstackElasticsearchIngestProcessorGsubResult
	err := ctx.Invoke("elasticstack:index/elasticstackElasticsearchIngestProcessorGsub:ElasticstackElasticsearchIngestProcessorGsub", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking ElasticstackElasticsearchIngestProcessorGsub.
type ElasticstackElasticsearchIngestProcessorGsubArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to apply the replacement to.
	Field string `pulumi:"field"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// The pattern to be replaced.
	Pattern string `pulumi:"pattern"`
	// The string to replace the matching patterns with.
	Replacement string `pulumi:"replacement"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField *string `pulumi:"targetField"`
}

// A collection of values returned by ElasticstackElasticsearchIngestProcessorGsub.
type ElasticstackElasticsearchIngestProcessorGsubResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to apply the replacement to.
	Field string `pulumi:"field"`
	// Internal identifier of the resource.
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// The pattern to be replaced.
	Pattern string `pulumi:"pattern"`
	// The string to replace the matching patterns with.
	Replacement string `pulumi:"replacement"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField *string `pulumi:"targetField"`
}

func ElasticstackElasticsearchIngestProcessorGsubOutput(ctx *pulumi.Context, args ElasticstackElasticsearchIngestProcessorGsubOutputArgs, opts ...pulumi.InvokeOption) ElasticstackElasticsearchIngestProcessorGsubResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ElasticstackElasticsearchIngestProcessorGsubResult, error) {
			args := v.(ElasticstackElasticsearchIngestProcessorGsubArgs)
			r, err := ElasticstackElasticsearchIngestProcessorGsub(ctx, &args, opts...)
			var s ElasticstackElasticsearchIngestProcessorGsubResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(ElasticstackElasticsearchIngestProcessorGsubResultOutput)
}

// A collection of arguments for invoking ElasticstackElasticsearchIngestProcessorGsub.
type ElasticstackElasticsearchIngestProcessorGsubOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The field to apply the replacement to.
	Field pulumi.StringInput `pulumi:"field"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing pulumi.BoolPtrInput `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// The pattern to be replaced.
	Pattern pulumi.StringInput `pulumi:"pattern"`
	// The string to replace the matching patterns with.
	Replacement pulumi.StringInput `pulumi:"replacement"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField pulumi.StringPtrInput `pulumi:"targetField"`
}

func (ElasticstackElasticsearchIngestProcessorGsubOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchIngestProcessorGsubArgs)(nil)).Elem()
}

// A collection of values returned by ElasticstackElasticsearchIngestProcessorGsub.
type ElasticstackElasticsearchIngestProcessorGsubResultOutput struct{ *pulumi.OutputState }

func (ElasticstackElasticsearchIngestProcessorGsubResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchIngestProcessorGsubResult)(nil)).Elem()
}

func (o ElasticstackElasticsearchIngestProcessorGsubResultOutput) ToElasticstackElasticsearchIngestProcessorGsubResultOutput() ElasticstackElasticsearchIngestProcessorGsubResultOutput {
	return o
}

func (o ElasticstackElasticsearchIngestProcessorGsubResultOutput) ToElasticstackElasticsearchIngestProcessorGsubResultOutputWithContext(ctx context.Context) ElasticstackElasticsearchIngestProcessorGsubResultOutput {
	return o
}

// Description of the processor.
func (o ElasticstackElasticsearchIngestProcessorGsubResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorGsubResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The field to apply the replacement to.
func (o ElasticstackElasticsearchIngestProcessorGsubResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorGsubResult) string { return v.Field }).(pulumi.StringOutput)
}

// Internal identifier of the resource.
func (o ElasticstackElasticsearchIngestProcessorGsubResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorGsubResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o ElasticstackElasticsearchIngestProcessorGsubResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorGsubResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o ElasticstackElasticsearchIngestProcessorGsubResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorGsubResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
func (o ElasticstackElasticsearchIngestProcessorGsubResultOutput) IgnoreMissing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorGsubResult) *bool { return v.IgnoreMissing }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o ElasticstackElasticsearchIngestProcessorGsubResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorGsubResult) string { return v.Json }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o ElasticstackElasticsearchIngestProcessorGsubResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorGsubResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// The pattern to be replaced.
func (o ElasticstackElasticsearchIngestProcessorGsubResultOutput) Pattern() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorGsubResult) string { return v.Pattern }).(pulumi.StringOutput)
}

// The string to replace the matching patterns with.
func (o ElasticstackElasticsearchIngestProcessorGsubResultOutput) Replacement() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorGsubResult) string { return v.Replacement }).(pulumi.StringOutput)
}

// Identifier for the processor.
func (o ElasticstackElasticsearchIngestProcessorGsubResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorGsubResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// The field to assign the converted value to, by default `field` is updated in-place.
func (o ElasticstackElasticsearchIngestProcessorGsubResultOutput) TargetField() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorGsubResult) *string { return v.TargetField }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticstackElasticsearchIngestProcessorGsubResultOutput{})
}
