// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Helper data source to which can be used to create a processor to append one or more values to an existing array if the field already exists and it is an array.
// Converts a scalar to an array and appends one or more values to it if the field exists and it is a scalar. Creates an array containing the provided values if the field doesn’t exist.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/append-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			tags, err := elasticstack.ElasticstackElasticsearchIngestProcessorAppend(ctx, &elasticstack.ElasticstackElasticsearchIngestProcessorAppendArgs{
//				Field: "tags",
//				Values: []string{
//					"production",
//					"{{{app}}}",
//					"{{{owner}}}",
//				},
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = elasticstack.NewElasticstackElasticsearchIngestPipeline(ctx, "myIngestPipeline", &elasticstack.ElasticstackElasticsearchIngestPipelineArgs{
//				Processors: pulumi.StringArray{
//					*pulumi.String(tags.Json),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func ElasticstackElasticsearchIngestProcessorAppend(ctx *pulumi.Context, args *ElasticstackElasticsearchIngestProcessorAppendArgs, opts ...pulumi.InvokeOption) (*ElasticstackElasticsearchIngestProcessorAppendResult, error) {
	var rv ElasticstackElasticsearchIngestProcessorAppendResult
	err := ctx.Invoke("elasticstack:index/elasticstackElasticsearchIngestProcessorAppend:ElasticstackElasticsearchIngestProcessorAppend", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking ElasticstackElasticsearchIngestProcessorAppend.
type ElasticstackElasticsearchIngestProcessorAppendArgs struct {
	// If `false`, the processor does not append values already present in the field.
	AllowDuplicates *bool `pulumi:"allowDuplicates"`
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to be appended to.
	Field string `pulumi:"field"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// The media type for encoding value. Applies only when value is a template snippet. Must be one of `application/json`, `text/plain`, or `application/x-www-form-urlencoded`. Supported only from Elasticsearch version **7.15**.
	MediaType *string `pulumi:"mediaType"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The value to be appended.
	Values []string `pulumi:"values"`
}

// A collection of values returned by ElasticstackElasticsearchIngestProcessorAppend.
type ElasticstackElasticsearchIngestProcessorAppendResult struct {
	// If `false`, the processor does not append values already present in the field.
	AllowDuplicates *bool `pulumi:"allowDuplicates"`
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to be appended to.
	Field string `pulumi:"field"`
	// Internal identifier of the resource
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// The media type for encoding value. Applies only when value is a template snippet. Must be one of `application/json`, `text/plain`, or `application/x-www-form-urlencoded`. Supported only from Elasticsearch version **7.15**.
	MediaType *string `pulumi:"mediaType"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The value to be appended.
	Values []string `pulumi:"values"`
}

func ElasticstackElasticsearchIngestProcessorAppendOutput(ctx *pulumi.Context, args ElasticstackElasticsearchIngestProcessorAppendOutputArgs, opts ...pulumi.InvokeOption) ElasticstackElasticsearchIngestProcessorAppendResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ElasticstackElasticsearchIngestProcessorAppendResult, error) {
			args := v.(ElasticstackElasticsearchIngestProcessorAppendArgs)
			r, err := ElasticstackElasticsearchIngestProcessorAppend(ctx, &args, opts...)
			var s ElasticstackElasticsearchIngestProcessorAppendResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(ElasticstackElasticsearchIngestProcessorAppendResultOutput)
}

// A collection of arguments for invoking ElasticstackElasticsearchIngestProcessorAppend.
type ElasticstackElasticsearchIngestProcessorAppendOutputArgs struct {
	// If `false`, the processor does not append values already present in the field.
	AllowDuplicates pulumi.BoolPtrInput `pulumi:"allowDuplicates"`
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The field to be appended to.
	Field pulumi.StringInput `pulumi:"field"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// The media type for encoding value. Applies only when value is a template snippet. Must be one of `application/json`, `text/plain`, or `application/x-www-form-urlencoded`. Supported only from Elasticsearch version **7.15**.
	MediaType pulumi.StringPtrInput `pulumi:"mediaType"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// The value to be appended.
	Values pulumi.StringArrayInput `pulumi:"values"`
}

func (ElasticstackElasticsearchIngestProcessorAppendOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchIngestProcessorAppendArgs)(nil)).Elem()
}

// A collection of values returned by ElasticstackElasticsearchIngestProcessorAppend.
type ElasticstackElasticsearchIngestProcessorAppendResultOutput struct{ *pulumi.OutputState }

func (ElasticstackElasticsearchIngestProcessorAppendResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchIngestProcessorAppendResult)(nil)).Elem()
}

func (o ElasticstackElasticsearchIngestProcessorAppendResultOutput) ToElasticstackElasticsearchIngestProcessorAppendResultOutput() ElasticstackElasticsearchIngestProcessorAppendResultOutput {
	return o
}

func (o ElasticstackElasticsearchIngestProcessorAppendResultOutput) ToElasticstackElasticsearchIngestProcessorAppendResultOutputWithContext(ctx context.Context) ElasticstackElasticsearchIngestProcessorAppendResultOutput {
	return o
}

// If `false`, the processor does not append values already present in the field.
func (o ElasticstackElasticsearchIngestProcessorAppendResultOutput) AllowDuplicates() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorAppendResult) *bool { return v.AllowDuplicates }).(pulumi.BoolPtrOutput)
}

// Description of the processor.
func (o ElasticstackElasticsearchIngestProcessorAppendResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorAppendResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The field to be appended to.
func (o ElasticstackElasticsearchIngestProcessorAppendResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorAppendResult) string { return v.Field }).(pulumi.StringOutput)
}

// Internal identifier of the resource
func (o ElasticstackElasticsearchIngestProcessorAppendResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorAppendResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o ElasticstackElasticsearchIngestProcessorAppendResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorAppendResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o ElasticstackElasticsearchIngestProcessorAppendResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorAppendResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o ElasticstackElasticsearchIngestProcessorAppendResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorAppendResult) string { return v.Json }).(pulumi.StringOutput)
}

// The media type for encoding value. Applies only when value is a template snippet. Must be one of `application/json`, `text/plain`, or `application/x-www-form-urlencoded`. Supported only from Elasticsearch version **7.15**.
func (o ElasticstackElasticsearchIngestProcessorAppendResultOutput) MediaType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorAppendResult) *string { return v.MediaType }).(pulumi.StringPtrOutput)
}

// Handle failures for the processor.
func (o ElasticstackElasticsearchIngestProcessorAppendResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorAppendResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// Identifier for the processor.
func (o ElasticstackElasticsearchIngestProcessorAppendResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorAppendResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// The value to be appended.
func (o ElasticstackElasticsearchIngestProcessorAppendResultOutput) Values() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorAppendResult) []string { return v.Values }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticstackElasticsearchIngestProcessorAppendResultOutput{})
}
