// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Removes HTML tags from the field. If the field is an array of strings, HTML tags will be removed from all members of the array.
//
// See: templates/data-sources/elasticsearch_ingest_processor_html_strip.md.tmpl
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			htmlStrip, err := elasticstack.ElasticstackElasticsearchIngestProcessorHtmlStrip(ctx, &elasticstack.ElasticstackElasticsearchIngestProcessorHtmlStripArgs{
//				Field: "foo",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = elasticstack.NewElasticstackElasticsearchIngestPipeline(ctx, "myIngestPipeline", &elasticstack.ElasticstackElasticsearchIngestPipelineArgs{
//				Processors: pulumi.StringArray{
//					*pulumi.String(htmlStrip.Json),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func ElasticstackElasticsearchIngestProcessorHtmlStrip(ctx *pulumi.Context, args *ElasticstackElasticsearchIngestProcessorHtmlStripArgs, opts ...pulumi.InvokeOption) (*ElasticstackElasticsearchIngestProcessorHtmlStripResult, error) {
	var rv ElasticstackElasticsearchIngestProcessorHtmlStripResult
	err := ctx.Invoke("elasticstack:index/elasticstackElasticsearchIngestProcessorHtmlStrip:ElasticstackElasticsearchIngestProcessorHtmlStrip", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking ElasticstackElasticsearchIngestProcessorHtmlStrip.
type ElasticstackElasticsearchIngestProcessorHtmlStripArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to apply the replacement to.
	Field string `pulumi:"field"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField *string `pulumi:"targetField"`
}

// A collection of values returned by ElasticstackElasticsearchIngestProcessorHtmlStrip.
type ElasticstackElasticsearchIngestProcessorHtmlStripResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to apply the replacement to.
	Field string `pulumi:"field"`
	// Internal identifier of the resource.
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField *string `pulumi:"targetField"`
}

func ElasticstackElasticsearchIngestProcessorHtmlStripOutput(ctx *pulumi.Context, args ElasticstackElasticsearchIngestProcessorHtmlStripOutputArgs, opts ...pulumi.InvokeOption) ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ElasticstackElasticsearchIngestProcessorHtmlStripResult, error) {
			args := v.(ElasticstackElasticsearchIngestProcessorHtmlStripArgs)
			r, err := ElasticstackElasticsearchIngestProcessorHtmlStrip(ctx, &args, opts...)
			var s ElasticstackElasticsearchIngestProcessorHtmlStripResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput)
}

// A collection of arguments for invoking ElasticstackElasticsearchIngestProcessorHtmlStrip.
type ElasticstackElasticsearchIngestProcessorHtmlStripOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The field to apply the replacement to.
	Field pulumi.StringInput `pulumi:"field"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing pulumi.BoolPtrInput `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField pulumi.StringPtrInput `pulumi:"targetField"`
}

func (ElasticstackElasticsearchIngestProcessorHtmlStripOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchIngestProcessorHtmlStripArgs)(nil)).Elem()
}

// A collection of values returned by ElasticstackElasticsearchIngestProcessorHtmlStrip.
type ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput struct{ *pulumi.OutputState }

func (ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchIngestProcessorHtmlStripResult)(nil)).Elem()
}

func (o ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput) ToElasticstackElasticsearchIngestProcessorHtmlStripResultOutput() ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput {
	return o
}

func (o ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput) ToElasticstackElasticsearchIngestProcessorHtmlStripResultOutputWithContext(ctx context.Context) ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput {
	return o
}

// Description of the processor.
func (o ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorHtmlStripResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The field to apply the replacement to.
func (o ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorHtmlStripResult) string { return v.Field }).(pulumi.StringOutput)
}

// Internal identifier of the resource.
func (o ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorHtmlStripResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorHtmlStripResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorHtmlStripResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
func (o ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput) IgnoreMissing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorHtmlStripResult) *bool { return v.IgnoreMissing }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorHtmlStripResult) string { return v.Json }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorHtmlStripResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// Identifier for the processor.
func (o ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorHtmlStripResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// The field to assign the converted value to, by default `field` is updated in-place.
func (o ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput) TargetField() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorHtmlStripResult) *string { return v.TargetField }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticstackElasticsearchIngestProcessorHtmlStripResultOutput{})
}
