// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Executes another pipeline.
//
// The name of the current pipeline can be accessed from the `_ingest.pipeline` ingest metadata key.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/pipeline-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			appendTags, err := elasticstack.ElasticstackElasticsearchIngestProcessorAppend(ctx, &elasticstack.ElasticstackElasticsearchIngestProcessorAppendArgs{
//				Field: "tags",
//				Values: []string{
//					"production",
//					"{{{app}}}",
//					"{{{owner}}}",
//				},
//			}, nil)
//			if err != nil {
//				return err
//			}
//			pipelineA, err := elasticstack.NewElasticstackElasticsearchIngestPipeline(ctx, "pipelineA", &elasticstack.ElasticstackElasticsearchIngestPipelineArgs{
//				Processors: pulumi.StringArray{
//					*pulumi.String(appendTags.Json),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			fingerprint, err := elasticstack.ElasticstackElasticsearchIngestProcessorFingerprint(ctx, &elasticstack.ElasticstackElasticsearchIngestProcessorFingerprintArgs{
//				Fields: []string{
//					"owner",
//				},
//			}, nil)
//			if err != nil {
//				return err
//			}
//			pipeline := elasticstack.ElasticstackElasticsearchIngestProcessorPipelineOutput(ctx, elasticstack.ElasticstackElasticsearchIngestProcessorPipelineOutputArgs{
//				Name: pipelineA.Name,
//			}, nil)
//			_, err = elasticstack.NewElasticstackElasticsearchIngestPipeline(ctx, "pipelineB", &elasticstack.ElasticstackElasticsearchIngestPipelineArgs{
//				Processors: pulumi.StringArray{
//					pipeline.ApplyT(func(pipeline elasticstack.ElasticstackElasticsearchIngestProcessorPipelineResult) (*string, error) {
//						return &pipeline.Json, nil
//					}).(pulumi.StringPtrOutput),
//					*pulumi.String(fingerprint.Json),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func ElasticstackElasticsearchIngestProcessorPipeline(ctx *pulumi.Context, args *ElasticstackElasticsearchIngestProcessorPipelineArgs, opts ...pulumi.InvokeOption) (*ElasticstackElasticsearchIngestProcessorPipelineResult, error) {
	var rv ElasticstackElasticsearchIngestProcessorPipelineResult
	err := ctx.Invoke("elasticstack:index/elasticstackElasticsearchIngestProcessorPipeline:ElasticstackElasticsearchIngestProcessorPipeline", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking ElasticstackElasticsearchIngestProcessorPipeline.
type ElasticstackElasticsearchIngestProcessorPipelineArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// The name of the pipeline to execute.
	Name string `pulumi:"name"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
}

// A collection of values returned by ElasticstackElasticsearchIngestProcessorPipeline.
type ElasticstackElasticsearchIngestProcessorPipelineResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// Internal identifier of the resource.
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// The name of the pipeline to execute.
	Name string `pulumi:"name"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
}

func ElasticstackElasticsearchIngestProcessorPipelineOutput(ctx *pulumi.Context, args ElasticstackElasticsearchIngestProcessorPipelineOutputArgs, opts ...pulumi.InvokeOption) ElasticstackElasticsearchIngestProcessorPipelineResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ElasticstackElasticsearchIngestProcessorPipelineResult, error) {
			args := v.(ElasticstackElasticsearchIngestProcessorPipelineArgs)
			r, err := ElasticstackElasticsearchIngestProcessorPipeline(ctx, &args, opts...)
			var s ElasticstackElasticsearchIngestProcessorPipelineResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(ElasticstackElasticsearchIngestProcessorPipelineResultOutput)
}

// A collection of arguments for invoking ElasticstackElasticsearchIngestProcessorPipeline.
type ElasticstackElasticsearchIngestProcessorPipelineOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// The name of the pipeline to execute.
	Name pulumi.StringInput `pulumi:"name"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
}

func (ElasticstackElasticsearchIngestProcessorPipelineOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchIngestProcessorPipelineArgs)(nil)).Elem()
}

// A collection of values returned by ElasticstackElasticsearchIngestProcessorPipeline.
type ElasticstackElasticsearchIngestProcessorPipelineResultOutput struct{ *pulumi.OutputState }

func (ElasticstackElasticsearchIngestProcessorPipelineResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchIngestProcessorPipelineResult)(nil)).Elem()
}

func (o ElasticstackElasticsearchIngestProcessorPipelineResultOutput) ToElasticstackElasticsearchIngestProcessorPipelineResultOutput() ElasticstackElasticsearchIngestProcessorPipelineResultOutput {
	return o
}

func (o ElasticstackElasticsearchIngestProcessorPipelineResultOutput) ToElasticstackElasticsearchIngestProcessorPipelineResultOutputWithContext(ctx context.Context) ElasticstackElasticsearchIngestProcessorPipelineResultOutput {
	return o
}

// Description of the processor.
func (o ElasticstackElasticsearchIngestProcessorPipelineResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorPipelineResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// Internal identifier of the resource.
func (o ElasticstackElasticsearchIngestProcessorPipelineResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorPipelineResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o ElasticstackElasticsearchIngestProcessorPipelineResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorPipelineResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o ElasticstackElasticsearchIngestProcessorPipelineResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorPipelineResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o ElasticstackElasticsearchIngestProcessorPipelineResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorPipelineResult) string { return v.Json }).(pulumi.StringOutput)
}

// The name of the pipeline to execute.
func (o ElasticstackElasticsearchIngestProcessorPipelineResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorPipelineResult) string { return v.Name }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o ElasticstackElasticsearchIngestProcessorPipelineResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorPipelineResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// Identifier for the processor.
func (o ElasticstackElasticsearchIngestProcessorPipelineResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorPipelineResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticstackElasticsearchIngestProcessorPipelineResultOutput{})
}
