// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Sets one field and associates it with the specified value. If the field already exists, its value will be replaced with the provided one.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/set-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			set, err := elasticstack.ElasticstackElasticsearchIngestProcessorSet(ctx, &elasticstack.ElasticstackElasticsearchIngestProcessorSetArgs{
//				Field: "count",
//				Value: pulumi.StringRef("1"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = elasticstack.NewElasticstackElasticsearchIngestPipeline(ctx, "myIngestPipeline", &elasticstack.ElasticstackElasticsearchIngestPipelineArgs{
//				Processors: pulumi.StringArray{
//					*pulumi.String(set.Json),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func ElasticstackElasticsearchIngestProcessorSet(ctx *pulumi.Context, args *ElasticstackElasticsearchIngestProcessorSetArgs, opts ...pulumi.InvokeOption) (*ElasticstackElasticsearchIngestProcessorSetResult, error) {
	var rv ElasticstackElasticsearchIngestProcessorSetResult
	err := ctx.Invoke("elasticstack:index/elasticstackElasticsearchIngestProcessorSet:ElasticstackElasticsearchIngestProcessorSet", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking ElasticstackElasticsearchIngestProcessorSet.
type ElasticstackElasticsearchIngestProcessorSetArgs struct {
	// The origin field which will be copied to `field`, cannot set `value` simultaneously.
	CopyFrom *string `pulumi:"copyFrom"`
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to insert, upsert, or update.
	Field string `pulumi:"field"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// If `true` and `value` is a template snippet that evaluates to `null` or the empty string, the processor quietly exits without modifying the document
	IgnoreEmptyValue *bool `pulumi:"ignoreEmptyValue"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// The media type for encoding value.
	MediaType *string `pulumi:"mediaType"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// If processor will update fields with pre-existing non-null-valued field.
	Override *bool `pulumi:"override"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The value to be set for the field. Supports template snippets. May specify only one of `value` or `copyFrom`.
	Value *string `pulumi:"value"`
}

// A collection of values returned by ElasticstackElasticsearchIngestProcessorSet.
type ElasticstackElasticsearchIngestProcessorSetResult struct {
	// The origin field which will be copied to `field`, cannot set `value` simultaneously.
	CopyFrom *string `pulumi:"copyFrom"`
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to insert, upsert, or update.
	Field string `pulumi:"field"`
	// Internal identifier of the resource.
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// If `true` and `value` is a template snippet that evaluates to `null` or the empty string, the processor quietly exits without modifying the document
	IgnoreEmptyValue *bool `pulumi:"ignoreEmptyValue"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// The media type for encoding value.
	MediaType *string `pulumi:"mediaType"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// If processor will update fields with pre-existing non-null-valued field.
	Override *bool `pulumi:"override"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The value to be set for the field. Supports template snippets. May specify only one of `value` or `copyFrom`.
	Value *string `pulumi:"value"`
}

func ElasticstackElasticsearchIngestProcessorSetOutput(ctx *pulumi.Context, args ElasticstackElasticsearchIngestProcessorSetOutputArgs, opts ...pulumi.InvokeOption) ElasticstackElasticsearchIngestProcessorSetResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ElasticstackElasticsearchIngestProcessorSetResult, error) {
			args := v.(ElasticstackElasticsearchIngestProcessorSetArgs)
			r, err := ElasticstackElasticsearchIngestProcessorSet(ctx, &args, opts...)
			var s ElasticstackElasticsearchIngestProcessorSetResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(ElasticstackElasticsearchIngestProcessorSetResultOutput)
}

// A collection of arguments for invoking ElasticstackElasticsearchIngestProcessorSet.
type ElasticstackElasticsearchIngestProcessorSetOutputArgs struct {
	// The origin field which will be copied to `field`, cannot set `value` simultaneously.
	CopyFrom pulumi.StringPtrInput `pulumi:"copyFrom"`
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The field to insert, upsert, or update.
	Field pulumi.StringInput `pulumi:"field"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// If `true` and `value` is a template snippet that evaluates to `null` or the empty string, the processor quietly exits without modifying the document
	IgnoreEmptyValue pulumi.BoolPtrInput `pulumi:"ignoreEmptyValue"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// The media type for encoding value.
	MediaType pulumi.StringPtrInput `pulumi:"mediaType"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// If processor will update fields with pre-existing non-null-valued field.
	Override pulumi.BoolPtrInput `pulumi:"override"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// The value to be set for the field. Supports template snippets. May specify only one of `value` or `copyFrom`.
	Value pulumi.StringPtrInput `pulumi:"value"`
}

func (ElasticstackElasticsearchIngestProcessorSetOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchIngestProcessorSetArgs)(nil)).Elem()
}

// A collection of values returned by ElasticstackElasticsearchIngestProcessorSet.
type ElasticstackElasticsearchIngestProcessorSetResultOutput struct{ *pulumi.OutputState }

func (ElasticstackElasticsearchIngestProcessorSetResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchIngestProcessorSetResult)(nil)).Elem()
}

func (o ElasticstackElasticsearchIngestProcessorSetResultOutput) ToElasticstackElasticsearchIngestProcessorSetResultOutput() ElasticstackElasticsearchIngestProcessorSetResultOutput {
	return o
}

func (o ElasticstackElasticsearchIngestProcessorSetResultOutput) ToElasticstackElasticsearchIngestProcessorSetResultOutputWithContext(ctx context.Context) ElasticstackElasticsearchIngestProcessorSetResultOutput {
	return o
}

// The origin field which will be copied to `field`, cannot set `value` simultaneously.
func (o ElasticstackElasticsearchIngestProcessorSetResultOutput) CopyFrom() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorSetResult) *string { return v.CopyFrom }).(pulumi.StringPtrOutput)
}

// Description of the processor.
func (o ElasticstackElasticsearchIngestProcessorSetResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorSetResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The field to insert, upsert, or update.
func (o ElasticstackElasticsearchIngestProcessorSetResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorSetResult) string { return v.Field }).(pulumi.StringOutput)
}

// Internal identifier of the resource.
func (o ElasticstackElasticsearchIngestProcessorSetResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorSetResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o ElasticstackElasticsearchIngestProcessorSetResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorSetResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// If `true` and `value` is a template snippet that evaluates to `null` or the empty string, the processor quietly exits without modifying the document
func (o ElasticstackElasticsearchIngestProcessorSetResultOutput) IgnoreEmptyValue() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorSetResult) *bool { return v.IgnoreEmptyValue }).(pulumi.BoolPtrOutput)
}

// Ignore failures for the processor.
func (o ElasticstackElasticsearchIngestProcessorSetResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorSetResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o ElasticstackElasticsearchIngestProcessorSetResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorSetResult) string { return v.Json }).(pulumi.StringOutput)
}

// The media type for encoding value.
func (o ElasticstackElasticsearchIngestProcessorSetResultOutput) MediaType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorSetResult) *string { return v.MediaType }).(pulumi.StringPtrOutput)
}

// Handle failures for the processor.
func (o ElasticstackElasticsearchIngestProcessorSetResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorSetResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// If processor will update fields with pre-existing non-null-valued field.
func (o ElasticstackElasticsearchIngestProcessorSetResultOutput) Override() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorSetResult) *bool { return v.Override }).(pulumi.BoolPtrOutput)
}

// Identifier for the processor.
func (o ElasticstackElasticsearchIngestProcessorSetResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorSetResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// The value to be set for the field. Supports template snippets. May specify only one of `value` or `copyFrom`.
func (o ElasticstackElasticsearchIngestProcessorSetResultOutput) Value() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorSetResult) *string { return v.Value }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticstackElasticsearchIngestProcessorSetResultOutput{})
}
