// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Renames an existing field. If the field doesn’t exist or the new name is already used, an exception will be thrown.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/rename-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			rename, err := elasticstack.ElasticstackElasticsearchIngestProcessorRename(ctx, &elasticstack.ElasticstackElasticsearchIngestProcessorRenameArgs{
//				Field:       "provider",
//				TargetField: "cloud.provider",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = elasticstack.NewElasticstackElasticsearchIngestPipeline(ctx, "myIngestPipeline", &elasticstack.ElasticstackElasticsearchIngestPipelineArgs{
//				Processors: pulumi.StringArray{
//					*pulumi.String(rename.Json),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func ElasticstackElasticsearchIngestProcessorRename(ctx *pulumi.Context, args *ElasticstackElasticsearchIngestProcessorRenameArgs, opts ...pulumi.InvokeOption) (*ElasticstackElasticsearchIngestProcessorRenameResult, error) {
	var rv ElasticstackElasticsearchIngestProcessorRenameResult
	err := ctx.Invoke("elasticstack:index/elasticstackElasticsearchIngestProcessorRename:ElasticstackElasticsearchIngestProcessorRename", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking ElasticstackElasticsearchIngestProcessorRename.
type ElasticstackElasticsearchIngestProcessorRenameArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to be renamed.
	Field string `pulumi:"field"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The new name of the field.
	TargetField string `pulumi:"targetField"`
}

// A collection of values returned by ElasticstackElasticsearchIngestProcessorRename.
type ElasticstackElasticsearchIngestProcessorRenameResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to be renamed.
	Field string `pulumi:"field"`
	// Internal identifier of the resource.
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The new name of the field.
	TargetField string `pulumi:"targetField"`
}

func ElasticstackElasticsearchIngestProcessorRenameOutput(ctx *pulumi.Context, args ElasticstackElasticsearchIngestProcessorRenameOutputArgs, opts ...pulumi.InvokeOption) ElasticstackElasticsearchIngestProcessorRenameResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ElasticstackElasticsearchIngestProcessorRenameResult, error) {
			args := v.(ElasticstackElasticsearchIngestProcessorRenameArgs)
			r, err := ElasticstackElasticsearchIngestProcessorRename(ctx, &args, opts...)
			var s ElasticstackElasticsearchIngestProcessorRenameResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(ElasticstackElasticsearchIngestProcessorRenameResultOutput)
}

// A collection of arguments for invoking ElasticstackElasticsearchIngestProcessorRename.
type ElasticstackElasticsearchIngestProcessorRenameOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The field to be renamed.
	Field pulumi.StringInput `pulumi:"field"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing pulumi.BoolPtrInput `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// The new name of the field.
	TargetField pulumi.StringInput `pulumi:"targetField"`
}

func (ElasticstackElasticsearchIngestProcessorRenameOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchIngestProcessorRenameArgs)(nil)).Elem()
}

// A collection of values returned by ElasticstackElasticsearchIngestProcessorRename.
type ElasticstackElasticsearchIngestProcessorRenameResultOutput struct{ *pulumi.OutputState }

func (ElasticstackElasticsearchIngestProcessorRenameResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchIngestProcessorRenameResult)(nil)).Elem()
}

func (o ElasticstackElasticsearchIngestProcessorRenameResultOutput) ToElasticstackElasticsearchIngestProcessorRenameResultOutput() ElasticstackElasticsearchIngestProcessorRenameResultOutput {
	return o
}

func (o ElasticstackElasticsearchIngestProcessorRenameResultOutput) ToElasticstackElasticsearchIngestProcessorRenameResultOutputWithContext(ctx context.Context) ElasticstackElasticsearchIngestProcessorRenameResultOutput {
	return o
}

// Description of the processor.
func (o ElasticstackElasticsearchIngestProcessorRenameResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRenameResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The field to be renamed.
func (o ElasticstackElasticsearchIngestProcessorRenameResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRenameResult) string { return v.Field }).(pulumi.StringOutput)
}

// Internal identifier of the resource.
func (o ElasticstackElasticsearchIngestProcessorRenameResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRenameResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o ElasticstackElasticsearchIngestProcessorRenameResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRenameResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o ElasticstackElasticsearchIngestProcessorRenameResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRenameResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
func (o ElasticstackElasticsearchIngestProcessorRenameResultOutput) IgnoreMissing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRenameResult) *bool { return v.IgnoreMissing }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o ElasticstackElasticsearchIngestProcessorRenameResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRenameResult) string { return v.Json }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o ElasticstackElasticsearchIngestProcessorRenameResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRenameResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// Identifier for the processor.
func (o ElasticstackElasticsearchIngestProcessorRenameResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRenameResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// The new name of the field.
func (o ElasticstackElasticsearchIngestProcessorRenameResultOutput) TargetField() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRenameResult) string { return v.TargetField }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticstackElasticsearchIngestProcessorRenameResultOutput{})
}
