// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to get information about existing Elasticsearch user. See, https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-get-user.html".
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			userElasticstackElasticsearchDataSecurityUser, err := elasticstack.ElasticstackElasticsearchDataSecurityUser(ctx, &elasticstack.ElasticstackElasticsearchDataSecurityUserArgs{
//				Username: "elastic",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("user", userElasticstackElasticsearchDataSecurityUser)
//			return nil
//		})
//	}
//
// ```
func ElasticstackElasticsearchDataSecurityUser(ctx *pulumi.Context, args *ElasticstackElasticsearchDataSecurityUserArgs, opts ...pulumi.InvokeOption) (*ElasticstackElasticsearchDataSecurityUserResult, error) {
	var rv ElasticstackElasticsearchDataSecurityUserResult
	err := ctx.Invoke("elasticstack:index/elasticstackElasticsearchDataSecurityUser:ElasticstackElasticsearchDataSecurityUser", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking ElasticstackElasticsearchDataSecurityUser.
type ElasticstackElasticsearchDataSecurityUserArgs struct {
	// Elasticsearch connection configuration block.
	ElasticsearchConnection *ElasticstackElasticsearchDataSecurityUserElasticsearchConnection `pulumi:"elasticsearchConnection"`
	// An identifier for the user
	Username string `pulumi:"username"`
}

// A collection of values returned by ElasticstackElasticsearchDataSecurityUser.
type ElasticstackElasticsearchDataSecurityUserResult struct {
	// Elasticsearch connection configuration block.
	ElasticsearchConnection *ElasticstackElasticsearchDataSecurityUserElasticsearchConnection `pulumi:"elasticsearchConnection"`
	// The email of the user.
	Email string `pulumi:"email"`
	// Specifies whether the user is enabled. The default value is true.
	Enabled bool `pulumi:"enabled"`
	// The full name of the user.
	FullName string `pulumi:"fullName"`
	// Internal identifier of the resource
	Id string `pulumi:"id"`
	// Arbitrary metadata that you want to associate with the user.
	Metadata string `pulumi:"metadata"`
	// A set of roles the user has. The roles determine the user’s access permissions. Default is [].
	Roles []string `pulumi:"roles"`
	// An identifier for the user
	Username string `pulumi:"username"`
}

func ElasticstackElasticsearchDataSecurityUserOutput(ctx *pulumi.Context, args ElasticstackElasticsearchDataSecurityUserOutputArgs, opts ...pulumi.InvokeOption) ElasticstackElasticsearchDataSecurityUserResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ElasticstackElasticsearchDataSecurityUserResult, error) {
			args := v.(ElasticstackElasticsearchDataSecurityUserArgs)
			r, err := ElasticstackElasticsearchDataSecurityUser(ctx, &args, opts...)
			var s ElasticstackElasticsearchDataSecurityUserResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(ElasticstackElasticsearchDataSecurityUserResultOutput)
}

// A collection of arguments for invoking ElasticstackElasticsearchDataSecurityUser.
type ElasticstackElasticsearchDataSecurityUserOutputArgs struct {
	// Elasticsearch connection configuration block.
	ElasticsearchConnection ElasticstackElasticsearchDataSecurityUserElasticsearchConnectionPtrInput `pulumi:"elasticsearchConnection"`
	// An identifier for the user
	Username pulumi.StringInput `pulumi:"username"`
}

func (ElasticstackElasticsearchDataSecurityUserOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchDataSecurityUserArgs)(nil)).Elem()
}

// A collection of values returned by ElasticstackElasticsearchDataSecurityUser.
type ElasticstackElasticsearchDataSecurityUserResultOutput struct{ *pulumi.OutputState }

func (ElasticstackElasticsearchDataSecurityUserResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchDataSecurityUserResult)(nil)).Elem()
}

func (o ElasticstackElasticsearchDataSecurityUserResultOutput) ToElasticstackElasticsearchDataSecurityUserResultOutput() ElasticstackElasticsearchDataSecurityUserResultOutput {
	return o
}

func (o ElasticstackElasticsearchDataSecurityUserResultOutput) ToElasticstackElasticsearchDataSecurityUserResultOutputWithContext(ctx context.Context) ElasticstackElasticsearchDataSecurityUserResultOutput {
	return o
}

// Elasticsearch connection configuration block.
func (o ElasticstackElasticsearchDataSecurityUserResultOutput) ElasticsearchConnection() ElasticstackElasticsearchDataSecurityUserElasticsearchConnectionPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchDataSecurityUserResult) *ElasticstackElasticsearchDataSecurityUserElasticsearchConnection {
		return v.ElasticsearchConnection
	}).(ElasticstackElasticsearchDataSecurityUserElasticsearchConnectionPtrOutput)
}

// The email of the user.
func (o ElasticstackElasticsearchDataSecurityUserResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchDataSecurityUserResult) string { return v.Email }).(pulumi.StringOutput)
}

// Specifies whether the user is enabled. The default value is true.
func (o ElasticstackElasticsearchDataSecurityUserResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchDataSecurityUserResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// The full name of the user.
func (o ElasticstackElasticsearchDataSecurityUserResultOutput) FullName() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchDataSecurityUserResult) string { return v.FullName }).(pulumi.StringOutput)
}

// Internal identifier of the resource
func (o ElasticstackElasticsearchDataSecurityUserResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchDataSecurityUserResult) string { return v.Id }).(pulumi.StringOutput)
}

// Arbitrary metadata that you want to associate with the user.
func (o ElasticstackElasticsearchDataSecurityUserResultOutput) Metadata() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchDataSecurityUserResult) string { return v.Metadata }).(pulumi.StringOutput)
}

// A set of roles the user has. The roles determine the user’s access permissions. Default is [].
func (o ElasticstackElasticsearchDataSecurityUserResultOutput) Roles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchDataSecurityUserResult) []string { return v.Roles }).(pulumi.StringArrayOutput)
}

// An identifier for the user
func (o ElasticstackElasticsearchDataSecurityUserResultOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchDataSecurityUserResult) string { return v.Username }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticstackElasticsearchDataSecurityUserResultOutput{})
}
