// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Removes existing fields. If one field doesn’t exist, an exception will be thrown.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/remove-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			remove, err := elasticstack.ElasticstackElasticsearchIngestProcessorRemove(ctx, &elasticstack.ElasticstackElasticsearchIngestProcessorRemoveArgs{
//				Fields: []string{
//					"user_agent",
//					"url",
//				},
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = elasticstack.NewElasticstackElasticsearchIngestPipeline(ctx, "myIngestPipeline", &elasticstack.ElasticstackElasticsearchIngestPipelineArgs{
//				Processors: pulumi.StringArray{
//					*pulumi.String(remove.Json),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func ElasticstackElasticsearchIngestProcessorRemove(ctx *pulumi.Context, args *ElasticstackElasticsearchIngestProcessorRemoveArgs, opts ...pulumi.InvokeOption) (*ElasticstackElasticsearchIngestProcessorRemoveResult, error) {
	var rv ElasticstackElasticsearchIngestProcessorRemoveResult
	err := ctx.Invoke("elasticstack:index/elasticstackElasticsearchIngestProcessorRemove:ElasticstackElasticsearchIngestProcessorRemove", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking ElasticstackElasticsearchIngestProcessorRemove.
type ElasticstackElasticsearchIngestProcessorRemoveArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// Fields to be removed.
	Fields []string `pulumi:"fields"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
}

// A collection of values returned by ElasticstackElasticsearchIngestProcessorRemove.
type ElasticstackElasticsearchIngestProcessorRemoveResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// Fields to be removed.
	Fields []string `pulumi:"fields"`
	// Internal identifier of the resource.
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
}

func ElasticstackElasticsearchIngestProcessorRemoveOutput(ctx *pulumi.Context, args ElasticstackElasticsearchIngestProcessorRemoveOutputArgs, opts ...pulumi.InvokeOption) ElasticstackElasticsearchIngestProcessorRemoveResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ElasticstackElasticsearchIngestProcessorRemoveResult, error) {
			args := v.(ElasticstackElasticsearchIngestProcessorRemoveArgs)
			r, err := ElasticstackElasticsearchIngestProcessorRemove(ctx, &args, opts...)
			var s ElasticstackElasticsearchIngestProcessorRemoveResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(ElasticstackElasticsearchIngestProcessorRemoveResultOutput)
}

// A collection of arguments for invoking ElasticstackElasticsearchIngestProcessorRemove.
type ElasticstackElasticsearchIngestProcessorRemoveOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// Fields to be removed.
	Fields pulumi.StringArrayInput `pulumi:"fields"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing pulumi.BoolPtrInput `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
}

func (ElasticstackElasticsearchIngestProcessorRemoveOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchIngestProcessorRemoveArgs)(nil)).Elem()
}

// A collection of values returned by ElasticstackElasticsearchIngestProcessorRemove.
type ElasticstackElasticsearchIngestProcessorRemoveResultOutput struct{ *pulumi.OutputState }

func (ElasticstackElasticsearchIngestProcessorRemoveResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchIngestProcessorRemoveResult)(nil)).Elem()
}

func (o ElasticstackElasticsearchIngestProcessorRemoveResultOutput) ToElasticstackElasticsearchIngestProcessorRemoveResultOutput() ElasticstackElasticsearchIngestProcessorRemoveResultOutput {
	return o
}

func (o ElasticstackElasticsearchIngestProcessorRemoveResultOutput) ToElasticstackElasticsearchIngestProcessorRemoveResultOutputWithContext(ctx context.Context) ElasticstackElasticsearchIngestProcessorRemoveResultOutput {
	return o
}

// Description of the processor.
func (o ElasticstackElasticsearchIngestProcessorRemoveResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRemoveResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// Fields to be removed.
func (o ElasticstackElasticsearchIngestProcessorRemoveResultOutput) Fields() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRemoveResult) []string { return v.Fields }).(pulumi.StringArrayOutput)
}

// Internal identifier of the resource.
func (o ElasticstackElasticsearchIngestProcessorRemoveResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRemoveResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o ElasticstackElasticsearchIngestProcessorRemoveResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRemoveResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o ElasticstackElasticsearchIngestProcessorRemoveResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRemoveResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
func (o ElasticstackElasticsearchIngestProcessorRemoveResultOutput) IgnoreMissing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRemoveResult) *bool { return v.IgnoreMissing }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o ElasticstackElasticsearchIngestProcessorRemoveResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRemoveResult) string { return v.Json }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o ElasticstackElasticsearchIngestProcessorRemoveResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRemoveResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// Identifier for the processor.
func (o ElasticstackElasticsearchIngestProcessorRemoveResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorRemoveResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticstackElasticsearchIngestProcessorRemoveResultOutput{})
}
