// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Converts a string to its lowercase equivalent. If the field is an array of strings, all members of the array will be converted.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/lowercase-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			lowercase, err := elasticstack.ElasticstackElasticsearchIngestProcessorLowercase(ctx, &elasticstack.ElasticstackElasticsearchIngestProcessorLowercaseArgs{
//				Field: "foo",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = elasticstack.NewElasticstackElasticsearchIngestPipeline(ctx, "myIngestPipeline", &elasticstack.ElasticstackElasticsearchIngestPipelineArgs{
//				Processors: pulumi.StringArray{
//					*pulumi.String(lowercase.Json),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func ElasticstackElasticsearchIngestProcessorLowercase(ctx *pulumi.Context, args *ElasticstackElasticsearchIngestProcessorLowercaseArgs, opts ...pulumi.InvokeOption) (*ElasticstackElasticsearchIngestProcessorLowercaseResult, error) {
	var rv ElasticstackElasticsearchIngestProcessorLowercaseResult
	err := ctx.Invoke("elasticstack:index/elasticstackElasticsearchIngestProcessorLowercase:ElasticstackElasticsearchIngestProcessorLowercase", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking ElasticstackElasticsearchIngestProcessorLowercase.
type ElasticstackElasticsearchIngestProcessorLowercaseArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to make lowercase.
	Field string `pulumi:"field"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField *string `pulumi:"targetField"`
}

// A collection of values returned by ElasticstackElasticsearchIngestProcessorLowercase.
type ElasticstackElasticsearchIngestProcessorLowercaseResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to make lowercase.
	Field string `pulumi:"field"`
	// Internal identifier of the resource.
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField *string `pulumi:"targetField"`
}

func ElasticstackElasticsearchIngestProcessorLowercaseOutput(ctx *pulumi.Context, args ElasticstackElasticsearchIngestProcessorLowercaseOutputArgs, opts ...pulumi.InvokeOption) ElasticstackElasticsearchIngestProcessorLowercaseResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ElasticstackElasticsearchIngestProcessorLowercaseResult, error) {
			args := v.(ElasticstackElasticsearchIngestProcessorLowercaseArgs)
			r, err := ElasticstackElasticsearchIngestProcessorLowercase(ctx, &args, opts...)
			var s ElasticstackElasticsearchIngestProcessorLowercaseResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(ElasticstackElasticsearchIngestProcessorLowercaseResultOutput)
}

// A collection of arguments for invoking ElasticstackElasticsearchIngestProcessorLowercase.
type ElasticstackElasticsearchIngestProcessorLowercaseOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The field to make lowercase.
	Field pulumi.StringInput `pulumi:"field"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing pulumi.BoolPtrInput `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField pulumi.StringPtrInput `pulumi:"targetField"`
}

func (ElasticstackElasticsearchIngestProcessorLowercaseOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchIngestProcessorLowercaseArgs)(nil)).Elem()
}

// A collection of values returned by ElasticstackElasticsearchIngestProcessorLowercase.
type ElasticstackElasticsearchIngestProcessorLowercaseResultOutput struct{ *pulumi.OutputState }

func (ElasticstackElasticsearchIngestProcessorLowercaseResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticstackElasticsearchIngestProcessorLowercaseResult)(nil)).Elem()
}

func (o ElasticstackElasticsearchIngestProcessorLowercaseResultOutput) ToElasticstackElasticsearchIngestProcessorLowercaseResultOutput() ElasticstackElasticsearchIngestProcessorLowercaseResultOutput {
	return o
}

func (o ElasticstackElasticsearchIngestProcessorLowercaseResultOutput) ToElasticstackElasticsearchIngestProcessorLowercaseResultOutputWithContext(ctx context.Context) ElasticstackElasticsearchIngestProcessorLowercaseResultOutput {
	return o
}

// Description of the processor.
func (o ElasticstackElasticsearchIngestProcessorLowercaseResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorLowercaseResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The field to make lowercase.
func (o ElasticstackElasticsearchIngestProcessorLowercaseResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorLowercaseResult) string { return v.Field }).(pulumi.StringOutput)
}

// Internal identifier of the resource.
func (o ElasticstackElasticsearchIngestProcessorLowercaseResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorLowercaseResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o ElasticstackElasticsearchIngestProcessorLowercaseResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorLowercaseResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o ElasticstackElasticsearchIngestProcessorLowercaseResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorLowercaseResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
func (o ElasticstackElasticsearchIngestProcessorLowercaseResultOutput) IgnoreMissing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorLowercaseResult) *bool { return v.IgnoreMissing }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o ElasticstackElasticsearchIngestProcessorLowercaseResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorLowercaseResult) string { return v.Json }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o ElasticstackElasticsearchIngestProcessorLowercaseResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorLowercaseResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// Identifier for the processor.
func (o ElasticstackElasticsearchIngestProcessorLowercaseResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorLowercaseResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// The field to assign the converted value to, by default `field` is updated in-place.
func (o ElasticstackElasticsearchIngestProcessorLowercaseResultOutput) TargetField() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticstackElasticsearchIngestProcessorLowercaseResult) *string { return v.TargetField }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticstackElasticsearchIngestProcessorLowercaseResultOutput{})
}
