// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Removes HTML tags from the field. If the field is an array of strings, HTML tags will be removed from all members of the array.
//
// See: templates/data-sources/elasticsearch_ingest_processor_html_strip.md.tmpl
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/Tonkean/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			htmlStrip, err := elasticstack.IngestProcessorHtmlStrip(ctx, &elasticstack.IngestProcessorHtmlStripArgs{
//				Field: "foo",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = elasticstack.NewIngestPipeline(ctx, "myIngestPipeline", &elasticstack.IngestPipelineArgs{
//				Processors: pulumi.StringArray{
//					*pulumi.String(htmlStrip.Json),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func IngestProcessorHtmlStrip(ctx *pulumi.Context, args *IngestProcessorHtmlStripArgs, opts ...pulumi.InvokeOption) (*IngestProcessorHtmlStripResult, error) {
	var rv IngestProcessorHtmlStripResult
	err := ctx.Invoke("elasticstack:index/ingestProcessorHtmlStrip:IngestProcessorHtmlStrip", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking IngestProcessorHtmlStrip.
type IngestProcessorHtmlStripArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to apply the replacement to.
	Field string `pulumi:"field"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField *string `pulumi:"targetField"`
}

// A collection of values returned by IngestProcessorHtmlStrip.
type IngestProcessorHtmlStripResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to apply the replacement to.
	Field string `pulumi:"field"`
	// Internal identifier of the resource.
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField *string `pulumi:"targetField"`
}

func IngestProcessorHtmlStripOutput(ctx *pulumi.Context, args IngestProcessorHtmlStripOutputArgs, opts ...pulumi.InvokeOption) IngestProcessorHtmlStripResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (IngestProcessorHtmlStripResult, error) {
			args := v.(IngestProcessorHtmlStripArgs)
			r, err := IngestProcessorHtmlStrip(ctx, &args, opts...)
			var s IngestProcessorHtmlStripResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(IngestProcessorHtmlStripResultOutput)
}

// A collection of arguments for invoking IngestProcessorHtmlStrip.
type IngestProcessorHtmlStripOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The field to apply the replacement to.
	Field pulumi.StringInput `pulumi:"field"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing pulumi.BoolPtrInput `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField pulumi.StringPtrInput `pulumi:"targetField"`
}

func (IngestProcessorHtmlStripOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*IngestProcessorHtmlStripArgs)(nil)).Elem()
}

// A collection of values returned by IngestProcessorHtmlStrip.
type IngestProcessorHtmlStripResultOutput struct{ *pulumi.OutputState }

func (IngestProcessorHtmlStripResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*IngestProcessorHtmlStripResult)(nil)).Elem()
}

func (o IngestProcessorHtmlStripResultOutput) ToIngestProcessorHtmlStripResultOutput() IngestProcessorHtmlStripResultOutput {
	return o
}

func (o IngestProcessorHtmlStripResultOutput) ToIngestProcessorHtmlStripResultOutputWithContext(ctx context.Context) IngestProcessorHtmlStripResultOutput {
	return o
}

// Description of the processor.
func (o IngestProcessorHtmlStripResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorHtmlStripResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The field to apply the replacement to.
func (o IngestProcessorHtmlStripResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorHtmlStripResult) string { return v.Field }).(pulumi.StringOutput)
}

// Internal identifier of the resource.
func (o IngestProcessorHtmlStripResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorHtmlStripResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o IngestProcessorHtmlStripResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorHtmlStripResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o IngestProcessorHtmlStripResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v IngestProcessorHtmlStripResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
func (o IngestProcessorHtmlStripResultOutput) IgnoreMissing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v IngestProcessorHtmlStripResult) *bool { return v.IgnoreMissing }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o IngestProcessorHtmlStripResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorHtmlStripResult) string { return v.Json }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o IngestProcessorHtmlStripResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v IngestProcessorHtmlStripResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// Identifier for the processor.
func (o IngestProcessorHtmlStripResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorHtmlStripResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// The field to assign the converted value to, by default `field` is updated in-place.
func (o IngestProcessorHtmlStripResultOutput) TargetField() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorHtmlStripResult) *string { return v.TargetField }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(IngestProcessorHtmlStripResultOutput{})
}
