// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Extracts structured fields out of a single text field within a document. You choose which field to extract matched fields from, as well as the grok pattern you expect will match. A grok pattern is like a regular expression that supports aliased expressions that can be reused.
//
// This processor comes packaged with many [reusable patterns](https://github.com/elastic/elasticsearch/blob/master/libs/grok/src/main/resources/patterns).
//
// If you need help building patterns to match your logs, you will find the [Grok Debugger](https://www.elastic.co/guide/en/kibana/master/xpack-grokdebugger.html) tool quite useful! [The Grok Constructor](https://grokconstructor.appspot.com/) is also a useful tool.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/grok-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"fmt"
//
//	"github.com/Tonkean/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			grok, err := elasticstack.IngestProcessorGrok(ctx, &elasticstack.IngestProcessorGrokArgs{
//				Field: "message",
//				Patterns: []string{
//					fmt.Sprintf("%vFAVORITE_DOG:pet}", "%{"),
//					fmt.Sprintf("%vFAVORITE_CAT:pet}", "%{"),
//				},
//				PatternDefinitions: map[string]interface{}{
//					"FAVORITE_DOG": "beagle",
//					"FAVORITE_CAT": "burmese",
//				},
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = elasticstack.NewIngestPipeline(ctx, "myIngestPipeline", &elasticstack.IngestPipelineArgs{
//				Processors: pulumi.StringArray{
//					*pulumi.String(grok.Json),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func IngestProcessorGrok(ctx *pulumi.Context, args *IngestProcessorGrokArgs, opts ...pulumi.InvokeOption) (*IngestProcessorGrokResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv IngestProcessorGrokResult
	err := ctx.Invoke("elasticstack:index/ingestProcessorGrok:IngestProcessorGrok", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking IngestProcessorGrok.
type IngestProcessorGrokArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// Must be disabled or v1. If v1, the processor uses patterns with Elastic Common Schema (ECS) field names. **NOTE:** Supported only starting from version of Elasticsearch **7.16.x**.
	EcsCompatibility *string `pulumi:"ecsCompatibility"`
	// The field to use for grok expression parsing
	Field string `pulumi:"field"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// A map of pattern-name and pattern tuples defining custom patterns to be used by the current processor. Patterns matching existing names will override the pre-existing definition.
	PatternDefinitions map[string]string `pulumi:"patternDefinitions"`
	// An ordered list of grok expression to match and extract named captures with. Returns on the first expression in the list that matches.
	Patterns []string `pulumi:"patterns"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// when true, `_ingest._grok_match_index` will be inserted into your matched document’s metadata with the index into the pattern found in `patterns` that matched.
	TraceMatch *bool `pulumi:"traceMatch"`
}

// A collection of values returned by IngestProcessorGrok.
type IngestProcessorGrokResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// Must be disabled or v1. If v1, the processor uses patterns with Elastic Common Schema (ECS) field names. **NOTE:** Supported only starting from version of Elasticsearch **7.16.x**.
	EcsCompatibility *string `pulumi:"ecsCompatibility"`
	// The field to use for grok expression parsing
	Field string `pulumi:"field"`
	// Internal identifier of the resource
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// A map of pattern-name and pattern tuples defining custom patterns to be used by the current processor. Patterns matching existing names will override the pre-existing definition.
	PatternDefinitions map[string]string `pulumi:"patternDefinitions"`
	// An ordered list of grok expression to match and extract named captures with. Returns on the first expression in the list that matches.
	Patterns []string `pulumi:"patterns"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// when true, `_ingest._grok_match_index` will be inserted into your matched document’s metadata with the index into the pattern found in `patterns` that matched.
	TraceMatch *bool `pulumi:"traceMatch"`
}

func IngestProcessorGrokOutput(ctx *pulumi.Context, args IngestProcessorGrokOutputArgs, opts ...pulumi.InvokeOption) IngestProcessorGrokResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (IngestProcessorGrokResult, error) {
			args := v.(IngestProcessorGrokArgs)
			r, err := IngestProcessorGrok(ctx, &args, opts...)
			var s IngestProcessorGrokResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(IngestProcessorGrokResultOutput)
}

// A collection of arguments for invoking IngestProcessorGrok.
type IngestProcessorGrokOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// Must be disabled or v1. If v1, the processor uses patterns with Elastic Common Schema (ECS) field names. **NOTE:** Supported only starting from version of Elasticsearch **7.16.x**.
	EcsCompatibility pulumi.StringPtrInput `pulumi:"ecsCompatibility"`
	// The field to use for grok expression parsing
	Field pulumi.StringInput `pulumi:"field"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document
	IgnoreMissing pulumi.BoolPtrInput `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// A map of pattern-name and pattern tuples defining custom patterns to be used by the current processor. Patterns matching existing names will override the pre-existing definition.
	PatternDefinitions pulumi.StringMapInput `pulumi:"patternDefinitions"`
	// An ordered list of grok expression to match and extract named captures with. Returns on the first expression in the list that matches.
	Patterns pulumi.StringArrayInput `pulumi:"patterns"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// when true, `_ingest._grok_match_index` will be inserted into your matched document’s metadata with the index into the pattern found in `patterns` that matched.
	TraceMatch pulumi.BoolPtrInput `pulumi:"traceMatch"`
}

func (IngestProcessorGrokOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*IngestProcessorGrokArgs)(nil)).Elem()
}

// A collection of values returned by IngestProcessorGrok.
type IngestProcessorGrokResultOutput struct{ *pulumi.OutputState }

func (IngestProcessorGrokResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*IngestProcessorGrokResult)(nil)).Elem()
}

func (o IngestProcessorGrokResultOutput) ToIngestProcessorGrokResultOutput() IngestProcessorGrokResultOutput {
	return o
}

func (o IngestProcessorGrokResultOutput) ToIngestProcessorGrokResultOutputWithContext(ctx context.Context) IngestProcessorGrokResultOutput {
	return o
}

// Description of the processor.
func (o IngestProcessorGrokResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorGrokResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// Must be disabled or v1. If v1, the processor uses patterns with Elastic Common Schema (ECS) field names. **NOTE:** Supported only starting from version of Elasticsearch **7.16.x**.
func (o IngestProcessorGrokResultOutput) EcsCompatibility() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorGrokResult) *string { return v.EcsCompatibility }).(pulumi.StringPtrOutput)
}

// The field to use for grok expression parsing
func (o IngestProcessorGrokResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorGrokResult) string { return v.Field }).(pulumi.StringOutput)
}

// Internal identifier of the resource
func (o IngestProcessorGrokResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorGrokResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o IngestProcessorGrokResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorGrokResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o IngestProcessorGrokResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v IngestProcessorGrokResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document
func (o IngestProcessorGrokResultOutput) IgnoreMissing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v IngestProcessorGrokResult) *bool { return v.IgnoreMissing }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o IngestProcessorGrokResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorGrokResult) string { return v.Json }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o IngestProcessorGrokResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v IngestProcessorGrokResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// A map of pattern-name and pattern tuples defining custom patterns to be used by the current processor. Patterns matching existing names will override the pre-existing definition.
func (o IngestProcessorGrokResultOutput) PatternDefinitions() pulumi.StringMapOutput {
	return o.ApplyT(func(v IngestProcessorGrokResult) map[string]string { return v.PatternDefinitions }).(pulumi.StringMapOutput)
}

// An ordered list of grok expression to match and extract named captures with. Returns on the first expression in the list that matches.
func (o IngestProcessorGrokResultOutput) Patterns() pulumi.StringArrayOutput {
	return o.ApplyT(func(v IngestProcessorGrokResult) []string { return v.Patterns }).(pulumi.StringArrayOutput)
}

// Identifier for the processor.
func (o IngestProcessorGrokResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorGrokResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// when true, `_ingest._grok_match_index` will be inserted into your matched document’s metadata with the index into the pattern found in `patterns` that matched.
func (o IngestProcessorGrokResultOutput) TraceMatch() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v IngestProcessorGrokResult) *bool { return v.TraceMatch }).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(IngestProcessorGrokResultOutput{})
}
