// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Converts a string to its lowercase equivalent. If the field is an array of strings, all members of the array will be converted.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/lowercase-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/Tonkean/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			lowercase, err := elasticstack.IngestProcessorLowercase(ctx, &elasticstack.IngestProcessorLowercaseArgs{
//				Field: "foo",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = elasticstack.NewIngestPipeline(ctx, "myIngestPipeline", &elasticstack.IngestPipelineArgs{
//				Processors: pulumi.StringArray{
//					*pulumi.String(lowercase.Json),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func IngestProcessorLowercase(ctx *pulumi.Context, args *IngestProcessorLowercaseArgs, opts ...pulumi.InvokeOption) (*IngestProcessorLowercaseResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv IngestProcessorLowercaseResult
	err := ctx.Invoke("elasticstack:index/ingestProcessorLowercase:IngestProcessorLowercase", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking IngestProcessorLowercase.
type IngestProcessorLowercaseArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to make lowercase.
	Field string `pulumi:"field"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField *string `pulumi:"targetField"`
}

// A collection of values returned by IngestProcessorLowercase.
type IngestProcessorLowercaseResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to make lowercase.
	Field string `pulumi:"field"`
	// Internal identifier of the resource.
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField *string `pulumi:"targetField"`
}

func IngestProcessorLowercaseOutput(ctx *pulumi.Context, args IngestProcessorLowercaseOutputArgs, opts ...pulumi.InvokeOption) IngestProcessorLowercaseResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (IngestProcessorLowercaseResult, error) {
			args := v.(IngestProcessorLowercaseArgs)
			r, err := IngestProcessorLowercase(ctx, &args, opts...)
			var s IngestProcessorLowercaseResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(IngestProcessorLowercaseResultOutput)
}

// A collection of arguments for invoking IngestProcessorLowercase.
type IngestProcessorLowercaseOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The field to make lowercase.
	Field pulumi.StringInput `pulumi:"field"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing pulumi.BoolPtrInput `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField pulumi.StringPtrInput `pulumi:"targetField"`
}

func (IngestProcessorLowercaseOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*IngestProcessorLowercaseArgs)(nil)).Elem()
}

// A collection of values returned by IngestProcessorLowercase.
type IngestProcessorLowercaseResultOutput struct{ *pulumi.OutputState }

func (IngestProcessorLowercaseResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*IngestProcessorLowercaseResult)(nil)).Elem()
}

func (o IngestProcessorLowercaseResultOutput) ToIngestProcessorLowercaseResultOutput() IngestProcessorLowercaseResultOutput {
	return o
}

func (o IngestProcessorLowercaseResultOutput) ToIngestProcessorLowercaseResultOutputWithContext(ctx context.Context) IngestProcessorLowercaseResultOutput {
	return o
}

// Description of the processor.
func (o IngestProcessorLowercaseResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorLowercaseResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The field to make lowercase.
func (o IngestProcessorLowercaseResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorLowercaseResult) string { return v.Field }).(pulumi.StringOutput)
}

// Internal identifier of the resource.
func (o IngestProcessorLowercaseResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorLowercaseResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o IngestProcessorLowercaseResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorLowercaseResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o IngestProcessorLowercaseResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v IngestProcessorLowercaseResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
func (o IngestProcessorLowercaseResultOutput) IgnoreMissing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v IngestProcessorLowercaseResult) *bool { return v.IgnoreMissing }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o IngestProcessorLowercaseResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorLowercaseResult) string { return v.Json }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o IngestProcessorLowercaseResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v IngestProcessorLowercaseResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// Identifier for the processor.
func (o IngestProcessorLowercaseResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorLowercaseResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// The field to assign the converted value to, by default `field` is updated in-place.
func (o IngestProcessorLowercaseResultOutput) TargetField() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorLowercaseResult) *string { return v.TargetField }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(IngestProcessorLowercaseResultOutput{})
}
