// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Helper data source to which can be used to create a processor to convert a human readable byte value (e.g. 1kb) to its value in bytes (e.g. 1024). If the field is an array of strings, all members of the array will be converted.
//
// Supported human readable units are "b", "kb", "mb", "gb", "tb", "pb" case insensitive. An error will occur if the field is not a supported format or resultant value exceeds 2^63.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/bytes-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/Tonkean/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			bytes, err := elasticstack.IngestProcessorBytes(ctx, &elasticstack.IngestProcessorBytesArgs{
//				Field: "file.size",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = elasticstack.NewIngestPipeline(ctx, "myIngestPipeline", &elasticstack.IngestPipelineArgs{
//				Processors: pulumi.StringArray{
//					*pulumi.String(bytes.Json),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func IngestProcessorBytes(ctx *pulumi.Context, args *IngestProcessorBytesArgs, opts ...pulumi.InvokeOption) (*IngestProcessorBytesResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv IngestProcessorBytesResult
	err := ctx.Invoke("elasticstack:index/ingestProcessorBytes:IngestProcessorBytes", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking IngestProcessorBytes.
type IngestProcessorBytesArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to convert
	Field string `pulumi:"field"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place
	TargetField *string `pulumi:"targetField"`
}

// A collection of values returned by IngestProcessorBytes.
type IngestProcessorBytesResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to convert
	Field string `pulumi:"field"`
	// Internal identifier of the resource
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place
	TargetField *string `pulumi:"targetField"`
}

func IngestProcessorBytesOutput(ctx *pulumi.Context, args IngestProcessorBytesOutputArgs, opts ...pulumi.InvokeOption) IngestProcessorBytesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (IngestProcessorBytesResult, error) {
			args := v.(IngestProcessorBytesArgs)
			r, err := IngestProcessorBytes(ctx, &args, opts...)
			var s IngestProcessorBytesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(IngestProcessorBytesResultOutput)
}

// A collection of arguments for invoking IngestProcessorBytes.
type IngestProcessorBytesOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The field to convert
	Field pulumi.StringInput `pulumi:"field"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing pulumi.BoolPtrInput `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place
	TargetField pulumi.StringPtrInput `pulumi:"targetField"`
}

func (IngestProcessorBytesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*IngestProcessorBytesArgs)(nil)).Elem()
}

// A collection of values returned by IngestProcessorBytes.
type IngestProcessorBytesResultOutput struct{ *pulumi.OutputState }

func (IngestProcessorBytesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*IngestProcessorBytesResult)(nil)).Elem()
}

func (o IngestProcessorBytesResultOutput) ToIngestProcessorBytesResultOutput() IngestProcessorBytesResultOutput {
	return o
}

func (o IngestProcessorBytesResultOutput) ToIngestProcessorBytesResultOutputWithContext(ctx context.Context) IngestProcessorBytesResultOutput {
	return o
}

// Description of the processor.
func (o IngestProcessorBytesResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorBytesResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The field to convert
func (o IngestProcessorBytesResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorBytesResult) string { return v.Field }).(pulumi.StringOutput)
}

// Internal identifier of the resource
func (o IngestProcessorBytesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorBytesResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o IngestProcessorBytesResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorBytesResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o IngestProcessorBytesResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v IngestProcessorBytesResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
func (o IngestProcessorBytesResultOutput) IgnoreMissing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v IngestProcessorBytesResult) *bool { return v.IgnoreMissing }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o IngestProcessorBytesResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorBytesResult) string { return v.Json }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o IngestProcessorBytesResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v IngestProcessorBytesResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// Identifier for the processor.
func (o IngestProcessorBytesResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorBytesResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// The field to assign the converted value to, by default `field` is updated in-place
func (o IngestProcessorBytesResultOutput) TargetField() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorBytesResult) *string { return v.TargetField }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(IngestProcessorBytesResultOutput{})
}
