// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Raises an exception. This is useful for when you expect a pipeline to fail and want to relay a specific message to the requester.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/fail-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/Tonkean/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			fail, err := elasticstack.IngestProcessorFail(ctx, &elasticstack.IngestProcessorFailArgs{
//				If:      pulumi.StringRef("ctx.tags.contains('production') != true"),
//				Message: "The production tag is not present, found tags: {{{tags}}}",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = elasticstack.NewIngestPipeline(ctx, "myIngestPipeline", &elasticstack.IngestPipelineArgs{
//				Processors: pulumi.StringArray{
//					*pulumi.String(fail.Json),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func IngestProcessorFail(ctx *pulumi.Context, args *IngestProcessorFailArgs, opts ...pulumi.InvokeOption) (*IngestProcessorFailResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv IngestProcessorFailResult
	err := ctx.Invoke("elasticstack:index/ingestProcessorFail:IngestProcessorFail", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking IngestProcessorFail.
type IngestProcessorFailArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// The error message thrown by the processor.
	Message string `pulumi:"message"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
}

// A collection of values returned by IngestProcessorFail.
type IngestProcessorFailResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// Internal identifier of the resource
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// The error message thrown by the processor.
	Message string `pulumi:"message"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
}

func IngestProcessorFailOutput(ctx *pulumi.Context, args IngestProcessorFailOutputArgs, opts ...pulumi.InvokeOption) IngestProcessorFailResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (IngestProcessorFailResult, error) {
			args := v.(IngestProcessorFailArgs)
			r, err := IngestProcessorFail(ctx, &args, opts...)
			var s IngestProcessorFailResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(IngestProcessorFailResultOutput)
}

// A collection of arguments for invoking IngestProcessorFail.
type IngestProcessorFailOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// The error message thrown by the processor.
	Message pulumi.StringInput `pulumi:"message"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
}

func (IngestProcessorFailOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*IngestProcessorFailArgs)(nil)).Elem()
}

// A collection of values returned by IngestProcessorFail.
type IngestProcessorFailResultOutput struct{ *pulumi.OutputState }

func (IngestProcessorFailResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*IngestProcessorFailResult)(nil)).Elem()
}

func (o IngestProcessorFailResultOutput) ToIngestProcessorFailResultOutput() IngestProcessorFailResultOutput {
	return o
}

func (o IngestProcessorFailResultOutput) ToIngestProcessorFailResultOutputWithContext(ctx context.Context) IngestProcessorFailResultOutput {
	return o
}

// Description of the processor.
func (o IngestProcessorFailResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorFailResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// Internal identifier of the resource
func (o IngestProcessorFailResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorFailResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o IngestProcessorFailResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorFailResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o IngestProcessorFailResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v IngestProcessorFailResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o IngestProcessorFailResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorFailResult) string { return v.Json }).(pulumi.StringOutput)
}

// The error message thrown by the processor.
func (o IngestProcessorFailResultOutput) Message() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorFailResult) string { return v.Message }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o IngestProcessorFailResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v IngestProcessorFailResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// Identifier for the processor.
func (o IngestProcessorFailResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorFailResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(IngestProcessorFailResultOutput{})
}
