// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Helper data source to which can be used to extract fields from CSV line out of a single text field within a document. Any empty field in CSV will be skipped.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/csv-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/Tonkean/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			csv, err := elasticstack.IngestProcessorCsv(ctx, &elasticstack.IngestProcessorCsvArgs{
//				Field: "my_field",
//				TargetFields: []string{
//					"field1",
//					"field2",
//				},
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = elasticstack.NewIngestPipeline(ctx, "myIngestPipeline", &elasticstack.IngestPipelineArgs{
//				Processors: pulumi.StringArray{
//					*pulumi.String(csv.Json),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// If the `trim` option is enabled then any whitespace in the beginning and in the end of each unquoted field will be trimmed. For example with configuration above, a value of A, B will result in field field2 having value {nbsp}B (with space at the beginning). If trim is enabled A, B will result in field field2 having value B (no whitespace). Quoted fields will be left untouched.
func IngestProcessorCsv(ctx *pulumi.Context, args *IngestProcessorCsvArgs, opts ...pulumi.InvokeOption) (*IngestProcessorCsvResult, error) {
	var rv IngestProcessorCsvResult
	err := ctx.Invoke("elasticstack:index/ingestProcessorCsv:IngestProcessorCsv", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking IngestProcessorCsv.
type IngestProcessorCsvArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// Value used to fill empty fields, empty fields will be skipped if this is not provided.
	EmptyValue *string `pulumi:"emptyValue"`
	// The field to extract data from.
	Field string `pulumi:"field"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Quote used in CSV, has to be single character string
	Quote *string `pulumi:"quote"`
	// Separator used in CSV, has to be single character string.
	Separator *string `pulumi:"separator"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The array of fields to assign extracted values to.
	TargetFields []string `pulumi:"targetFields"`
	// Trim whitespaces in unquoted fields.
	Trim *bool `pulumi:"trim"`
}

// A collection of values returned by IngestProcessorCsv.
type IngestProcessorCsvResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// Value used to fill empty fields, empty fields will be skipped if this is not provided.
	EmptyValue *string `pulumi:"emptyValue"`
	// The field to extract data from.
	Field string `pulumi:"field"`
	// Internal identifier of the resource
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Quote used in CSV, has to be single character string
	Quote *string `pulumi:"quote"`
	// Separator used in CSV, has to be single character string.
	Separator *string `pulumi:"separator"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The array of fields to assign extracted values to.
	TargetFields []string `pulumi:"targetFields"`
	// Trim whitespaces in unquoted fields.
	Trim *bool `pulumi:"trim"`
}

func IngestProcessorCsvOutput(ctx *pulumi.Context, args IngestProcessorCsvOutputArgs, opts ...pulumi.InvokeOption) IngestProcessorCsvResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (IngestProcessorCsvResult, error) {
			args := v.(IngestProcessorCsvArgs)
			r, err := IngestProcessorCsv(ctx, &args, opts...)
			var s IngestProcessorCsvResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(IngestProcessorCsvResultOutput)
}

// A collection of arguments for invoking IngestProcessorCsv.
type IngestProcessorCsvOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// Value used to fill empty fields, empty fields will be skipped if this is not provided.
	EmptyValue pulumi.StringPtrInput `pulumi:"emptyValue"`
	// The field to extract data from.
	Field pulumi.StringInput `pulumi:"field"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing pulumi.BoolPtrInput `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// Quote used in CSV, has to be single character string
	Quote pulumi.StringPtrInput `pulumi:"quote"`
	// Separator used in CSV, has to be single character string.
	Separator pulumi.StringPtrInput `pulumi:"separator"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// The array of fields to assign extracted values to.
	TargetFields pulumi.StringArrayInput `pulumi:"targetFields"`
	// Trim whitespaces in unquoted fields.
	Trim pulumi.BoolPtrInput `pulumi:"trim"`
}

func (IngestProcessorCsvOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*IngestProcessorCsvArgs)(nil)).Elem()
}

// A collection of values returned by IngestProcessorCsv.
type IngestProcessorCsvResultOutput struct{ *pulumi.OutputState }

func (IngestProcessorCsvResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*IngestProcessorCsvResult)(nil)).Elem()
}

func (o IngestProcessorCsvResultOutput) ToIngestProcessorCsvResultOutput() IngestProcessorCsvResultOutput {
	return o
}

func (o IngestProcessorCsvResultOutput) ToIngestProcessorCsvResultOutputWithContext(ctx context.Context) IngestProcessorCsvResultOutput {
	return o
}

// Description of the processor.
func (o IngestProcessorCsvResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorCsvResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// Value used to fill empty fields, empty fields will be skipped if this is not provided.
func (o IngestProcessorCsvResultOutput) EmptyValue() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorCsvResult) *string { return v.EmptyValue }).(pulumi.StringPtrOutput)
}

// The field to extract data from.
func (o IngestProcessorCsvResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorCsvResult) string { return v.Field }).(pulumi.StringOutput)
}

// Internal identifier of the resource
func (o IngestProcessorCsvResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorCsvResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o IngestProcessorCsvResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorCsvResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o IngestProcessorCsvResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v IngestProcessorCsvResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
func (o IngestProcessorCsvResultOutput) IgnoreMissing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v IngestProcessorCsvResult) *bool { return v.IgnoreMissing }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o IngestProcessorCsvResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorCsvResult) string { return v.Json }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o IngestProcessorCsvResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v IngestProcessorCsvResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// Quote used in CSV, has to be single character string
func (o IngestProcessorCsvResultOutput) Quote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorCsvResult) *string { return v.Quote }).(pulumi.StringPtrOutput)
}

// Separator used in CSV, has to be single character string.
func (o IngestProcessorCsvResultOutput) Separator() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorCsvResult) *string { return v.Separator }).(pulumi.StringPtrOutput)
}

// Identifier for the processor.
func (o IngestProcessorCsvResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorCsvResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// The array of fields to assign extracted values to.
func (o IngestProcessorCsvResultOutput) TargetFields() pulumi.StringArrayOutput {
	return o.ApplyT(func(v IngestProcessorCsvResult) []string { return v.TargetFields }).(pulumi.StringArrayOutput)
}

// Trim whitespaces in unquoted fields.
func (o IngestProcessorCsvResultOutput) Trim() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v IngestProcessorCsvResult) *bool { return v.Trim }).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(IngestProcessorCsvResultOutput{})
}
