// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Parses a Uniform Resource Identifier (URI) string and extracts its components as an object. This URI object includes properties for the URI’s domain, path, fragment, port, query, scheme, user info, username, and password.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/uri-parts-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/Tonkean/pulumi-elasticstack/sdk/go/elasticstack"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			parts, err := elasticstack.IngestProcessorUriParts(ctx, &elasticstack.IngestProcessorUriPartsArgs{
//				Field:              "input_field",
//				TargetField:        pulumi.StringRef("url"),
//				KeepOriginal:       pulumi.BoolRef(true),
//				RemoveIfSuccessful: pulumi.BoolRef(false),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = elasticstack.NewIngestPipeline(ctx, "myIngestPipeline", &elasticstack.IngestPipelineArgs{
//				Processors: pulumi.StringArray{
//					*pulumi.String(parts.Json),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func IngestProcessorUriParts(ctx *pulumi.Context, args *IngestProcessorUriPartsArgs, opts ...pulumi.InvokeOption) (*IngestProcessorUriPartsResult, error) {
	var rv IngestProcessorUriPartsResult
	err := ctx.Invoke("elasticstack:index/ingestProcessorUriParts:IngestProcessorUriParts", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking IngestProcessorUriParts.
type IngestProcessorUriPartsArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// Field containing the URI string.
	Field string `pulumi:"field"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If true, the processor copies the unparsed URI to `<target_field>.original.`
	KeepOriginal *bool `pulumi:"keepOriginal"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// If `true`, the processor removes the `field` after parsing the URI string. If parsing fails, the processor does not remove the `field`.
	RemoveIfSuccessful *bool `pulumi:"removeIfSuccessful"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// Output field for the URI object.
	TargetField *string `pulumi:"targetField"`
}

// A collection of values returned by IngestProcessorUriParts.
type IngestProcessorUriPartsResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// Field containing the URI string.
	Field string `pulumi:"field"`
	// Internal identifier of the resource.
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// If true, the processor copies the unparsed URI to `<target_field>.original.`
	KeepOriginal *bool `pulumi:"keepOriginal"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// If `true`, the processor removes the `field` after parsing the URI string. If parsing fails, the processor does not remove the `field`.
	RemoveIfSuccessful *bool `pulumi:"removeIfSuccessful"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// Output field for the URI object.
	TargetField *string `pulumi:"targetField"`
}

func IngestProcessorUriPartsOutput(ctx *pulumi.Context, args IngestProcessorUriPartsOutputArgs, opts ...pulumi.InvokeOption) IngestProcessorUriPartsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (IngestProcessorUriPartsResult, error) {
			args := v.(IngestProcessorUriPartsArgs)
			r, err := IngestProcessorUriParts(ctx, &args, opts...)
			var s IngestProcessorUriPartsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(IngestProcessorUriPartsResultOutput)
}

// A collection of arguments for invoking IngestProcessorUriParts.
type IngestProcessorUriPartsOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// Field containing the URI string.
	Field pulumi.StringInput `pulumi:"field"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// If true, the processor copies the unparsed URI to `<target_field>.original.`
	KeepOriginal pulumi.BoolPtrInput `pulumi:"keepOriginal"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// If `true`, the processor removes the `field` after parsing the URI string. If parsing fails, the processor does not remove the `field`.
	RemoveIfSuccessful pulumi.BoolPtrInput `pulumi:"removeIfSuccessful"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// Output field for the URI object.
	TargetField pulumi.StringPtrInput `pulumi:"targetField"`
}

func (IngestProcessorUriPartsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*IngestProcessorUriPartsArgs)(nil)).Elem()
}

// A collection of values returned by IngestProcessorUriParts.
type IngestProcessorUriPartsResultOutput struct{ *pulumi.OutputState }

func (IngestProcessorUriPartsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*IngestProcessorUriPartsResult)(nil)).Elem()
}

func (o IngestProcessorUriPartsResultOutput) ToIngestProcessorUriPartsResultOutput() IngestProcessorUriPartsResultOutput {
	return o
}

func (o IngestProcessorUriPartsResultOutput) ToIngestProcessorUriPartsResultOutputWithContext(ctx context.Context) IngestProcessorUriPartsResultOutput {
	return o
}

// Description of the processor.
func (o IngestProcessorUriPartsResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorUriPartsResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// Field containing the URI string.
func (o IngestProcessorUriPartsResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorUriPartsResult) string { return v.Field }).(pulumi.StringOutput)
}

// Internal identifier of the resource.
func (o IngestProcessorUriPartsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorUriPartsResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o IngestProcessorUriPartsResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorUriPartsResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o IngestProcessorUriPartsResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v IngestProcessorUriPartsResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o IngestProcessorUriPartsResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v IngestProcessorUriPartsResult) string { return v.Json }).(pulumi.StringOutput)
}

// If true, the processor copies the unparsed URI to `<target_field>.original.`
func (o IngestProcessorUriPartsResultOutput) KeepOriginal() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v IngestProcessorUriPartsResult) *bool { return v.KeepOriginal }).(pulumi.BoolPtrOutput)
}

// Handle failures for the processor.
func (o IngestProcessorUriPartsResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v IngestProcessorUriPartsResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// If `true`, the processor removes the `field` after parsing the URI string. If parsing fails, the processor does not remove the `field`.
func (o IngestProcessorUriPartsResultOutput) RemoveIfSuccessful() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v IngestProcessorUriPartsResult) *bool { return v.RemoveIfSuccessful }).(pulumi.BoolPtrOutput)
}

// Identifier for the processor.
func (o IngestProcessorUriPartsResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorUriPartsResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// Output field for the URI object.
func (o IngestProcessorUriPartsResultOutput) TargetField() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IngestProcessorUriPartsResult) *string { return v.TargetField }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(IngestProcessorUriPartsResultOutput{})
}
