// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use this data source to get information about existing Elasticsearch user. See, https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-get-user.html".
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as elasticstack from "@pulumi/elasticstack";
 *
 * const userDataSecurityUser = elasticstack.DataSecurityUser({
 *     username: "elastic",
 * });
 * export const user = userDataSecurityUser;
 * ```
 */
export function dataSecurityUser(args: DataSecurityUserArgs, opts?: pulumi.InvokeOptions): Promise<DataSecurityUserResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("elasticstack:index/dataSecurityUser:DataSecurityUser", {
        "elasticsearchConnection": args.elasticsearchConnection,
        "username": args.username,
    }, opts);
}

/**
 * A collection of arguments for invoking DataSecurityUser.
 */
export interface DataSecurityUserArgs {
    /**
     * Elasticsearch connection configuration block.
     */
    elasticsearchConnection?: inputs.DataSecurityUserElasticsearchConnection;
    /**
     * An identifier for the user
     */
    username: string;
}

/**
 * A collection of values returned by DataSecurityUser.
 */
export interface DataSecurityUserResult {
    /**
     * Elasticsearch connection configuration block.
     */
    readonly elasticsearchConnection?: outputs.DataSecurityUserElasticsearchConnection;
    /**
     * The email of the user.
     */
    readonly email: string;
    /**
     * Specifies whether the user is enabled. The default value is true.
     */
    readonly enabled: boolean;
    /**
     * The full name of the user.
     */
    readonly fullName: string;
    /**
     * Internal identifier of the resource
     */
    readonly id: string;
    /**
     * Arbitrary metadata that you want to associate with the user.
     */
    readonly metadata: string;
    /**
     * A set of roles the user has. The roles determine the user’s access permissions. Default is [].
     */
    readonly roles: string[];
    /**
     * An identifier for the user
     */
    readonly username: string;
}
/**
 * Use this data source to get information about existing Elasticsearch user. See, https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-get-user.html".
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as elasticstack from "@pulumi/elasticstack";
 *
 * const userDataSecurityUser = elasticstack.DataSecurityUser({
 *     username: "elastic",
 * });
 * export const user = userDataSecurityUser;
 * ```
 */
export function dataSecurityUserOutput(args: DataSecurityUserOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<DataSecurityUserResult> {
    return pulumi.output(args).apply((a: any) => dataSecurityUser(a, opts))
}

/**
 * A collection of arguments for invoking DataSecurityUser.
 */
export interface DataSecurityUserOutputArgs {
    /**
     * Elasticsearch connection configuration block.
     */
    elasticsearchConnection?: pulumi.Input<inputs.DataSecurityUserElasticsearchConnectionArgs>;
    /**
     * An identifier for the user
     */
    username: pulumi.Input<string>;
}
